const LIMIT_PRODUCTS_ON_PAGE = 9;
const DEFAULT_OFFSET = 0;
const DEFAULT_LIMIT = 0;
const DEFAULT_COUNT = 0;
const DEFAULT_TOTAL = 0;
const DEFAULT_PRICE = '0.00';
const CURRENCY_USD = '$';
const MAX_PRODUCT_LIMIT = 500;
const MIN_PRICE = 0;
const MAX_PRICE = 200;

export {
  LIMIT_PRODUCTS_ON_PAGE,
  DEFAULT_OFFSET,
  DEFAULT_PRICE,
  DEFAULT_LIMIT,
  DEFAULT_COUNT,
  DEFAULT_TOTAL,
  CURRENCY_USD,
  MAX_PRODUCT_LIMIT,
  MIN_PRICE,
  MAX_PRICE,
};
