const LIMIT_PRODUCTS_ON_PAGE = 20;
const DEFAULT_OFFSET = 0;
const DISCOUNT_PRICE = 0;
const DEFAULT_PRICE = '0.00';

export {
  LIMIT_PRODUCTS_ON_PAGE,
  DEFAULT_OFFSET,
  DISCOUNT_PRICE,
  DEFAULT_PRICE,
};
