export enum Endpoints {
  TOKEN = '/token',
  PASSWORD = '/password',
  TOKEN_ANONYMOUS = '/anonymous/token',
  PRODUCTS = '/products',
  CUSTOMERS = '/customers',
  ME = '/me',
  SIGN_UP_CUSTOMER = '/me/signup',
  LOGIN = '/me/login',
  OAUTH = '/oauth',
  CARTS = '/carts',
  ACTIVE_CART = 'active-cart',
  INTROSPECT = '/introspect',
  PRODUCT_INFORMATION = '/product-projections',
  PRODUCT_PROJECTIONS_SEARCH = '/product-projections/search',
  CATEGORIES = '/categories',
  DISCOUNT_CODES = '/discount-codes',
}
